#!/usr/bin/env python
from waflib import Utils

name = 'Charon.exe'

if bld.env.MCS and bld.env.DEST_OS != 'win32':
	name = 'charon.exe'
	bld.install_files('${BINDIR}', 'Charon', chmod=Utils.O755)

bld(
	features = 'cs',
	use = 'NLog.dll SharpPcap.dll Charon.Core.dll System.dll System.Xml.dll',
	source = bld.path.ant_glob('**/*.cs'),
	name = name,
	namespace = 'Charon',
	ver_product = 'Charon Fuzzing Platfom (based on Charon v3.0)',
	install = bld.path.ant_glob('template.xml samples/*')
)
