#!/usr/bin/env python

deps = [
	'Charon.Core.dll',
	'System.dll',
	'System.Core.dll',
	'System.Xml.dll',
	'NLog.dll',
	'Mono.Posix.dll',
]

bld(
	features = 'cs osx',
	use = deps,
	source = bld.path.ant_glob('**/*.cs'),
	name='Charon.Core.OS.OSX.dll',
)
