#!/usr/bin/env python

deps = [
	'System.dll',
	'System.Core.dll',
	'System.Runtime.Remoting.dll',
	'Charon.Core.dll',
	'Charon.Core.OS.Windows.dll',
]
bld(
	features = 'cs win',
	use = deps,
	source = bld.path.ant_glob('**/*.cs'),
	name='Charon.Core.WindowsDebugInstance.exe',
)

